---
version: "3"

tasks:
  default:
    deps: [ vendor:hugo, vendor:task ]
    desc: Vendor build executables
    cmds:
      - task: vendor:clean

  vendor:hugo:
    desc: Vendor hugo executable
    status:
      - stat hugo
    cmds:
      - wget https://github.com/gohugoio/hugo/releases/download/v0.112.3/hugo_0.112.3_Linux-64bit.tar.gz
      - tar -zxvf hugo_0.112.3_Linux-64bit.tar.gz hugo

  vendor:task:
    desc: Vendor task executable
    status:
      - stat task
    cmds:
      - wget https://github.com/go-task/task/releases/download/v3.25.0/task_linux_amd64.tar.gz
      - tar -zxvf task_linux_amd64.tar.gz task

  vendor:clean:
    internal: true
    cmds:
      - rm -f *.tar.gz