---
version: "3"

tasks:
  default:
    desc: Run hugo build
    cmds:
      - hugo --gc --minify --source=site -d public

  up:
    desc: Bring hugo down
    cmds:
      - docker compose up -d

  build:
    desc: Build hugo docker image
    cmds:
      - docker compose build

  down:
    desc: Bring hugo up
    cmds:
      - docker compose down
