---
version: "3"

tasks:
  default:
    deps: [ clone:ananke, clone:meghna ]
    desc: Ensure repos are cloned

  clone:ananke:
    internal: true
    status:
    - type ananke
    cmds:
    - git clone git@github.com:budparr/gohugo-theme-ananke.git ananke

  clone:meghna:
    internal: true
    status:
    - type meghna
    cmds:
    - git clone git@github.com:themefisher/meghna-hugo.git meghna
