---
version: "3"

tasks:
  default:
    deps: [ clone:ananke, clone:meghna ]
    desc: Ensure theme repos are cloned

  clone:ananke:
    internal: true
    status:
    - stat ananke
    cmds:
    - git clone https://github.com/budparr/gohugo-theme-ananke.git ananke

  clone:meghna:
    internal: true
    status:
    - stat meghna
    cmds:
    - git clone https://github.com/themefisher/meghna-hugo.git meghna
